services:
  - type: web
    name: smartpark-ai
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    autoDeploy: true
